---
image: registry.gitlab.com/lsm5/rpm-builder:latest

before_script:
     - cd $HOME/.ssh
     - openssl enc -aes-256-cbc -pbkdf2 -d -in id_rsa.enc -out id_rsa -pass pass:$DECRYPTION_PASSPHRASE
     - chmod 600 id_rsa
     - echo $FEDORA_KRB_PASSWORD | kinit lsm5@FEDORAPROJECT.ORG
     - mkdir -p $HOME/repositories/pkgs
     - cd $HOME/repositories/rpm-builder
     - git checkout rawhide
     - git pull

stages:
     - build

buildah:
     stage: build
     script:
          - bash builder.sh -t tagged -p buildah

container-selinux:
     stage: build
     script:
          - bash builder.sh -t tagged -p container-selinux

containernetworking-plugins:
     stage: build
     script:
          - bash builder.sh -t tagged -p containernetworking-plugins

fuse-overlayfs:
     stage: build
     script:
          - bash builder.sh -t tagged -p fuse-overlayfs

podman:
     stage: build
     script:
          - bash builder.sh -t tagged -p podman

slirp4netns:
     stage: build
     script:
          - bash builder.sh -t tagged -p slirp4netns
