---
image: registry.gitlab.com/lsm5/rpm-builder:f30

before_script:
     - sudo dnf update --nogpgcheck -y
     - sudo su lsm5-bot
     - export HOME=/home/lsm5-bot  
     - cd $HOME/.ssh
     - openssl enc -aes-256-cbc -pbkdf2 -d -in id_rsa.enc -out id_rsa -pass pass:$DECRYPTION_PASSPHRASE
     - chmod 600 id_rsa
     - echo $FEDORA_KRB_PASSWORD | kinit lsm5@FEDORAPROJECT.ORG
     - mkdir -p $HOME/repositories/pkgs
     - cd $HOME/repositories/rpm-builder
     - git checkout f30
     - git pull
     - git show HEAD

stages:
     - build

buildah:
     stage: build
     script:
          - bash builder.sh -t scratch -p buildah

container-selinux:
     stage: build
     script:
          - bash builder.sh -t scratch -p container-selinux

containernetworking-plugins:
     stage: build
     script:
          - bash builder.sh -t scratch -p containernetworking-plugins

fuse-overlayfs:
     stage: build
     script:
          - bash builder.sh -t scratch -p fuse-overlayfs

podman:
     stage: build
     script:
          - bash builder.sh -t scratch -p podman

slirp4netns:
     stage: build
     script:
          - bash builder.sh -t scratch -p slirp4netns
