---
image: registry.gitlab.com/lsm5/rpm-builder:bionic

before_script:
   - . /etc/os-release
   - cd $HOME/repositories/rpm-builder
   - git fetch --all
   - git checkout origin/$VERSION_CODENAME

stages:
     - build

buildah:
     stage: build
     script:
        - PACKAGE=buildah bash autobuilder.sh

conmon:
     stage: build
     script:
        - PACKAGE=conmon bash autobuilder.sh

containernetworking-plugins:
     stage: build
     script:
        - PACKAGE=containernetworking-plugins bash autobuilder.sh

cri-o-1.13:
     stage: build
     script:
        - PACKAGE=cri-o BRANCH=1.13 bash autobuilder.sh

cri-o-1.14:
     stage: build
     script:
        - PACKAGE=cri-o BRANCH=1.14 bash autobuilder.sh

cri-o-1.15:
     stage: build
     script:
        - PACKAGE=cri-o BRANCH=1.15 bash autobuilder.sh

podman:
     stage: build
     script:
        - PACKAGE=podman bash autobuilder.sh

skopeo:
     stage: build
     script:
        - PACKAGE=skopeo bash autobuilder.sh

