---
image: registry.gitlab.com/lsm5/rpm-builder:latest

before_script:
     - cd ~
     - openssl enc -aes-256-cbc -pbkdf2 -d -in .centos.cert.enc -out .centos.cert -pass pass:$DECRYPTION_PASSPHRASE
     - openssl enc -aes-256-cbc -pbkdf2 -d -in .centos-server-ca.cert.enc -out .centos-server-ca.cert -pass pass:$DECRYPTION_PASSPHRASE
     - cd ~/.ssh
     - openssl enc -aes-256-cbc -pbkdf2 -d -in id_rsa.enc -out id_rsa -pass pass:$DECRYPTION_PASSPHRASE
     - chmod 600 id_rsa
     - echo $FEDORA_KRB_PASSWORD | kinit lsm5@FEDORAPROJECT.ORG
     - mkdir -p ~/repositories/pkgs
     - cd ~/repositories/rpm-builder
     - git fetch --all
     - git checkout fedora-release
     - git pull

buildah-f29:
     script:
          - bash builder.sh -k f29 -t tagged -p buildah

buildah-f30:
     script:
          - bash builder.sh -k f30 -t tagged -p buildah

buildah-f31:
     script:
          - bash builder.sh -k f31 -t tagged -p buildah

container-selinux-f29:
     script:
          - bash builder.sh -k f29 -t tagged -p container-selinux

container-selinux-f30:
     script:
          - bash builder.sh -k f30 -t tagged -p container-selinux

container-selinux-f31:
     script:
          - bash builder.sh -k f31 -t tagged -p container-selinux

containernetworking-plugins-f29:
     script:
          - bash builder.sh -k f29 -t tagged -p containernetworking-plugins

containernetworking-plugins-f30:
     script:
          - bash builder.sh -k f30 -t tagged -p containernetworking-plugins

containernetworking-plugins-f31:
     script:
          - bash builder.sh -k f31 -t tagged -p containernetworking-plugins

fuse-overlayfs-f29:
     script:
          - bash builder.sh -k f29 -t tagged -p fuse-overlayfs

fuse-overlayfs-f30:
     script:
          - bash builder.sh -k f30 -t tagged -p fuse-overlayfs

fuse-overlayfs-f31:
     script:
          - bash builder.sh -k f31 -t tagged -p fuse-overlayfs

podman-f29:
     script:
          - bash builder.sh -k f29 -t tagged -p podman

podman-f30:
     script:
          - bash builder.sh -k f30 -t tagged -p podman

podman-f31:
     script:
          - bash builder.sh -k f31 -t tagged -p podman

skopeo-f29:
     script:
          - bash builder.sh -k f29 -t tagged -p skopeo

skopeo-f30:
     script:
          - bash builder.sh -k f30 -t tagged -p skopeo

skopeo-f31:
     script:
          - bash builder.sh -k f31 -t tagged -p skopeo

slirp4netns-f29:
     script:
          - bash builder.sh -k f29 -t tagged -p slirp4netns

slirp4netns-f30:
     script:
          - bash builder.sh -k f30 -t tagged -p slirp4netns

slirp4netns-f31:
     script:
          - bash builder.sh -k f31 -t tagged -p slirp4netns

