---

sudo: required

language: Generic

services:
    - docker

branches:
    only:
        - rawhide

env:
    global:
        - TRAVIS_ENV="-e TRAVIS=$TRAVIS
          -e CI=$CI -e TRAVIS_COMMIT=$TRAVIS_COMMIT
          -e TRAVIS_COMMIT_RANGE=$TRAVIS_COMMIT_RANGE
          -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
          -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
          -e TRAVIS_PULL_REQUEST_SHA=$TRAVIS_PULL_REQUEST_SHA
          -e TRAVIS_PULL_REQUEST_SLUG=$TRAVIS_PULL_REQUEST_SLUG
          -e TRAVIS_BRANCH=$TRAVIS_BRANCH
          -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID
          -e TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -qqy install realpath

jobs:
    include:
        - stage: build-fedora-rawhide
        - script:
            - env
            - echo "Building buildah in SPC using ./hack/run_build.sh"
            - "./hack/run_build.sh fedora rawhide buildah"
        - script:
            - env
            - echo "Building fuse-overlayfs in SPC using ./hack/run_build.sh"
            - "./hack/run_build.sh fedora rawhide fuse-overlayfs"
        - script:
            - env
            - echo "Building podman in SPC using ./hack/run_build.sh"
            - "./hack/run_build.sh fedora rawhide podman"
